### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by atribecalledkwest** [atribecalledkwest/karendoesthings-overlay#1]
- [x] OBS integration
- [x] Streamlabs integration
- [x] Flesh out background layouts system
- [ ] Test and potentially implement an animated background using `-webkit-mask-image` for masking.
- [ ] Replace placeholder art assets (such as the notify-panel image) with better-designed replacements.
- [ ] Replace current StreamLabs code with [nodecg-streamlabs](https://github.com/atribecalledkwest/nodecg-streamlabs)
